language: node_js
node_js:
  - "5"
before_install:
  - echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" > .npmrc
before_script:
  - npm config set spin false --global
  - npm install -g gulp
after_success:
  - ./release.sh
  - npm whoami
sudo: false
